### ISSUE TITLE
Sign releases with a production key (currently unclear how to 'upgrade' or re-install)

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri-installer-android#12]
Reported during 0.5.x hack session on Android 7:

Unable to install the .apk file if an existing installation of Kolibri is on the device. It doesn't re-install over it like the .pex or .exe file

Install Kolibri on Android device using .apk
1. Try installing a newer version of Kolibri on Android device using .apk
2. An error is shown by the android OS
3. The user had to uninstall the previous version to proceed

Sounds like part of the issue might have to do with signing certificates changing between builds. (cc @jamalex )

**Comment by DXCanas** [comment]
I think I've found out the way to handle this. Notes below. Some of the links provide outdated info (like the tools used to manually generate the keystore signature), but Android's documentation has a decent description of what's supposed to be used and how to do it. Going to try it first thing tomorrow.

I'm going to need some more information about the best way to handle a key that we're using to repeatedly build APK's -- I think it may be best to hold it inside of buildkite, so that everyone can just pull a signed APK from there. Going to need to talk to @aronasorman @jamalex for thoughts.
 
## Some Notes
Main issue: [apks are not signed, so android doesn't know they're _really_ the same app](https://stackoverflow.com/questions/16872355/remove-old-version-automatically-when-installing-new-one)

Resolution: [sign apk](https://developer.android.com/studio/publish/app-signing.html) (Steps 1, 3 , 4 -- 2 is taken care of by buildozer)
    [Lead here by kivy user group](https://groups.google.com/forum/#!topic/kivy-users/5-G7wkbHb_k)
    [Lead there by stackoverflow](https://stackoverflow.com/questions/23443740/sign-an-android-app-with-python-for-android-buildozer)

**Comment by indirectlylit** [comment]
> I'm going to need some more information about the best way to handle a key that we're using to repeatedly build APKs -- I think it may be best to hold it inside of buildkite, so that everyone can just pull a signed APK from there.

sounds good. we'll need similar functionality eventually for building signed windows installers - cc @mrpau-dev

**Comment by jamalex** [comment]
https://github.com/kivy/kivy/wiki/Creating-a-Release-APK

**Comment by DXCanas** [comment]
Seems like the p4a version described above is not the same as the one we're using. `--sign` isn't a valid argument for the toolchain we have.

**Comment by DXCanas** [comment]
Documentation above is a bit fuzzy, found a thread on buildozer's repo outlining some of the confusion: https://github.com/kivy/buildozer/issues/363
